name: EnchantmentLimiter
version: '1.0-SNAPSHOT'
main: org.conquest.enchantmentLimiter.EnchantmentLimiter
api-version: '1.21'
author: Conquest Coder
description: A plugin that handles limiting player enchantments from anvil and enchantment table

commands:
  el:
    description: Base command for EnchantmentLimiter
    usage: /<command>
    aliases: [enchantmentlimiter]
    permission: enchantmentlimiter.command
    permission-message: You do not have permission to use this command.
